### ISSUE TITLE
How to connect to the chip

### ISSUE THREAD

**Issue by fla-t** [pvvx/PHY62x2#1]
Not sure if this is the right place to ask you but, I want to hack a cheap smart watch into running my code (that is using phy6222qc).

The problem is that I dont know how to connect to it, you have mentioned a USB-COM/board in readme, but now details on what board or setup you used. I have a simple cp2102. But it does not have RTS port in it. 

Please help. 

Не уверен, что это подходящее место, чтобы спросить вас, но я хочу взломать дешевые умные часы и запустить мой код (то есть использовать phy6222qc).

Проблема в том, что я не знаю, как к нему подключиться, вы упомянули USB-COM/плату в файле readme, но теперь подробно о том, какую плату или настройку вы использовали. У меня простой cp2102. Но в нем нет порта RTS. 

Пожалуйста помоги.

**Comment by pvvx** [comment]
C USB-COM без RTS будет проблемно.
Как работать с [rdwr_phy62x2.py](https://github.com/pvvx/THB2/blob/master/rdwr_phy62x2.py) можно узнать и в [Сохранение оригинальной прошивки](https://github.com/pvvx/THB2/blob/master/README-ru.md#%D1%81%D0%BE%D1%85%D1%80%D0%B0%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BE%D1%80%D0%B8%D0%B3%D0%B8%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9-%D0%BF%D1%80%D0%BE%D1%88%D0%B8%D0%B2%D0%BA%D0%B8).

**Comment by fla-t** [comment]
@pvvx Can you also tell me what do you mean by a USB-COM device?

Можете ли вы также сказать мне, что вы подразумеваете под устройством USB-COM?

**Comment by pvvx** [comment]
> Can you also tell me what do you mean by a USB-COM device?

USB-COM port adapter, USB-UART adapter...

>  I have a simple cp2102. But it does not have RTS port in it.

The CP2102 chip has an RTS output.

![image](https://github.com/user-attachments/assets/8be4dcd2-c86e-4798-b99c-50748035d8c8)

**Comment by fla-t** [comment]
Thanks, @pvvx. One more thing. There is a github feature called discussions where people can ask/discuss things about the repos. Much like issues but it doesn't represent issues.

Would be great if you can enable that.

**Comment by fla-t** [comment]
My main goal is to be able to flash code, on the smartwatch that I bought. But I think the problem is my UART adapter. 

The one I have doesn't have the RTS pin. I will try to buy a new one that does have one.

Once thats done, I should be able to find my way around the code you wrote. 


Once again, Thanks @pvvx for doing Gods work <3

**Comment by cocus** [comment]
@fla-t , did you manage to test this out? I've bought a smartwatch that has a phy6222 and will try with a cheap cp2102 (or an ftdi with RTS). My main concern is the voltages. I haven't measured them, but wouldn't the target use the Vbatt for their IO? and my ftdi/cp2102 would use 3v3. Should I add some resistors in series to limit the voltage? (I don't want to use voltage translators)

**Comment by fla-t** [comment]
@cocus 

I was surprised about that too but shrug it off as a quirk of the watch.

I didn't got anywhere with the watch, I just left it and started on hacking its OTA protocol, decompiling their apps to get the binary.

But every app I decompiled gave me absolutely nothing every app said "the firmware is latest".

**Comment by Amir1387aht2** [comment]
> @cocus
> 
> I was surprised about that too but shrug it off as a quirk of the watch.
> 
> I didn't got anywhere with the watch, I just left it and started on hacking its OTA protocol, decompiling their apps to get the binary.
> 
> But every app I decompiled gave me absolutely nothing every app said "the firmware is latest".

you tried to hack FitPro App, right? I tried and I could change the server address(api) in app to get requests the app sends to in my own server, but i didn't continue due to reasons, i wanna ask, you guys wanna to work on it with together? 

Contact me on telegram : @Do3p3iri

**Comment by cocus** [comment]
Has any of you tried to use the APK of https://github.com/pvvx/PHY62x2/tree/master/App?

**Comment by Amir1387aht2** [comment]
> Has any of you tried to use the APK of https://github.com/pvvx/PHY62x2/tree/master/App?

If you wanna use it for your smartwatch, i don't recommend it, the first problem we have here is building firmware for it, and then there is a lot of ways to upload it

**Comment by cocus** [comment]
By the way, I was able to dump the flash of my device. The only thing I didn't connect was the TM pin; as soon as I connect that one, the tool doesn't work anymore.
For my particular variant (PHY6222QC-W04C), I've crafted the following command:
```
python3.exe rdwr_phy6222.py -p COM230 -b 250000 rc 0x11000000 0x00080000 ff_phy6222.bin
```

I'm using a FTDI adapter, not a cp2102; this particular breakout lets me set the VDDIO externally so I just tapped the VCC test pad for it (it's set to 3v3 by some LDO on the board, so I assume that's why it wasn't an issue to use any USB-UART adapter, as long as it's 3v3). Also note that I've tried 500kBps and 1MBps, but neither worked.

**Comment by fla-t** [comment]
@cocus interesting, so you didn't connected TM and it worked? I believe that TM for test mode and needs to pulled high.

When I tried it I connected all of the pins, even the TM. Let me try and remove.

**Comment by cocus** [comment]
> @cocus interesting, so you didn't connected TM and it worked? I believe that TM for test mode and needs to pulled high.
> 
> When I tried it I connected all of the pins, even the TM. Let me try and remove.

Yes, I know... but I did that, and it works :) try to run the identify command:

```
python3.exe rdwr_phy6222.py -p COM230 -b 9600 i
```

Note the quite conservative speed of 9600 bps, just in case.

**Comment by fla-t** [comment]
> Yes, I know... but I did that, and it works :) try to run the identify command:
> 
> ```
> python3.exe rdwr_phy6222.py -p COM230 -b 9600 i
> ```
> 
> Note the quite conservative speed of 9600 bps, just in case.

haha, I feel so happy. Its been sitting in the junk for far too long. TX jumper got broken, let me fix that I will get back to you.

**Comment by fla-t** [comment]
@cocus 

I am using mac so I changed the port:
```shell
python3 rdwr_phy6222.py -p /dev/tty.usbserial-A5XK3RJT -b 9600 i
```

it says: 
```text
=========================================================
PHY6222 Utility version 04.01.24
---------------------------------------------------------
Error: Open /dev/tty.usbserial-A5XK3RJT, 9600 baud!
```

**Comment by cocus** [comment]
try with sudo? (or whatever is the Mac equivalent for root permissions)

this is what's throwing an error in your case:
```

	def __init__(self, port='COM1'):
		self.old_erase_start = EXT_FLASH_ADD
		self.old_erase_end = EXT_FLASH_ADD
		self.port = port
		self.baud = START_BAUD
		try:
			self._port = serial.Serial(self.port, self.baud)
			self._port.timeout = 1
		except:
			print ('Error: Open %s, %d baud!' % (self.port, self.baud))
```

I was using an Admin console in my case.

**Comment by fla-t** [comment]
@cocus 

I booted up my PC for this and it worked.
```
=========================================================
PHY6222 Utility version 04.01.24
---------------------------------------------------------
Connecting...
PHY62x2 - Reset Ok
Revision: b'00136085 6222M005'
FlashID: 136085, size: 512 kbytes
PHY6222 - connected Ok
Reopen COM5 port 9600 baud... ok
```

**Comment by cocus** [comment]
That's good. Try to use 250000 as the baud, that worked for me. Did you leave the TM disconnected?

Now I'm trying to figure out what's on the flash dump I've got.

The 6222 has the following memory map:
![imagen](https://github.com/user-attachments/assets/3f0e4969-a975-48d7-be3c-e6029f8653fd)

I've dumped from 0x11000000, which is the start of the flash, and for 0x80000 bytes (512k).

Parsing stuff from the SDK sources, it seems like the GCC linker points to the following sections:

```
MEMORY
{
  jumptbl (rwx) : ORIGIN = 0x1fff0000, LENGTH = 1K
  gcfgtbl  (rwx) : ORIGIN = 0x1fff0400, LENGTH = 1K
  flash (rx) : ORIGIN = 0x11009000, LENGTH = 384K
  sram (rwx) : ORIGIN = 0x1fff1880, LENGTH = 59264
}
```
And then:
```
SECTIONS
{

    .textentry : {
        _stext = ABSOLUTE(.);
        *(*.isr_vector)
        *phy6222_start.o(.text)
    } > flash
```

Now, I know that `phy6222_start` is an assembly file with the following contents:
```

	.file		"phy6222_start.s"



.text
	.align	2
	.code	16
	.globl		__start
	.thumb_func
	.type	__start, %function
__start:

	ldr     r1,  =g_top_irqstack
	msr		msp, r1					/* r2>>sp */
	bl		c_start				/* R0=IRQ, R1=register save area on stack */


	.size	__start, .-__start
```

Then, the `isr_vector` is defined in `phy6222_vectors.c` as:
```
#define locate_data(n) __attribute__ ((section(n)))
extern unsigned int g_top_irqstack;
extern void __start(void);
const unsigned _vectors[] locate_data(".isr_vector") =
{
    /* Initial stack */

    (unsigned)(&g_top_irqstack),

    /* Reset exception handler */

    (unsigned)& __start,

};
```

With all of this in mind, I should expect the `isr_vector` at `0x11009000`:
```
ROM:11009000                 DCB 0x49
ROM:11009001                 DCB  0xA
ROM:11009002                 DCB 0xFF
ROM:11009003                 DCB 0x1F
ROM:11009004                 DCB 0x10
ROM:11009005                 DCB 0xB5
ROM:11009006                 DCB 0xFC
ROM:11009007                 DCB 0xF7
ROM:11009008                 DCB 0xD3
ROM:11009009                 DCB 0xFA
ROM:1100900A                 DCB 0xFF
ROM:1100900B                 DCB 0xF7
ROM:1100900C                 DCB 0xDB
ROM:1100900D                 DCB 0xF8
ROM:1100900E                 DCB 0
ROM:1100900F                 DCB 0x28 ; (
ROM:11009010                 DCB 1
ROM:11009011                 DCB 0xD0
ROM:11009012                 DCB 0xA
ROM:11009013                 DCB 0xF0
```

Re-arranging the first 4 bytes, it might yield a valid `g_top_irqstack` which its value is `0x1FFF0A49`. But then it falls apart because there is nothing "similar" to the init function shown there (I've checked that I'm in thumb mode).
If I re-interpret that start address as pure code, we have this:
```
ROM:11009000 ; ---------------------------------------------------------------------------
ROM:11009000                 LSRS            R1, R1, #9
ROM:11009002                 SUBS            R7, R7, #7
ROM:11009004                 PUSH            {R4,LR}
ROM:11009006                 BL              sub_110055B0
ROM:1100900A                 BL              sub_110081C4
ROM:1100900E                 CMP             R0, #0
ROM:11009010                 BEQ             loc_11009016
ROM:11009012                 BL              loc_11013070
```

I'm not sure if it's correct. I'll have to spend some time with this. Does anyone have any idea of this?

**Comment by fla-t** [comment]
The pyserial module in not a stdlib of python, it needs to be installed. The error messages were getting supressed and the vscode didn't show no warning.

**Comment by fla-t** [comment]
unfortunately as for me, I didn't reach that point yet. I will spend the night reading some of the SDK code to figure out.

one thing I don't understand is that numbers from the PDF and the one you shared with the SDK dont really match.

According to the PDF the flash should be 512k right? (I am probably missing something here I have a limited experience with this) 

Btw instead of decompiling the firmware, why don't just make some dummy programs and figure out that way? You already have a backup incase you flash it wrong or something

**Comment by cocus** [comment]
> one thing I don't understand is that numbers from the PDF and the one you shared with the SDK dont really match.

Yes, the documentation clearly states that flash starts at 0x11000000, as this is the number used on the scripts on this repo. Size is 0x00080000 because this particular chip (yours too) is 512k.
However, looking at the linker script for gcc, the flash starts at 0x11009000. To be honest, the first bytes of my dump are 0xff, up until 0x11001000, where there are some data, and then more 0xff.
I'm not certain about that. I have loaded Keil MDK to test this, and I've already compiled the GPIO example, I just need to study the map produced by it, to see where's everything on the resulting elf. I think the bootloader really requires that table to be at a given address for it to jump to the __start function.



> According to the PDF the flash should be 512k right? (I am probably missing something here I have a limited experience with this)

It's not according to the PDF, but rather the markings on your chip. Since you were able to run this tool, it already identified your chip as 512k as well (it should be marked as PHY6222QC-W04C; see the following image to figure how much capacity a given chip has).

![imagen](https://github.com/user-attachments/assets/dbc6a82a-fb1e-4bbf-aea4-cc0ccb6e1b07)
![imagen](https://github.com/user-attachments/assets/06ddab70-71a7-4d19-8ab1-65c25a0caca5)


> Btw instead of decompiling the firmware, why don't just make some dummy programs and figure out that way? You already have a backup incase you flash it wrong or something

Yes, you're correct. The problem is that I want to know which LCD controller they're using, since I have NO IDEA what is it, or how do they talk to it (SPI, I2C, using a peripheral or bitbanging GPIOs?). Does anyone have schematics for these cheap knock-off watches? Mine has a lp715_mb_v1.3 marking. I'm doing a reverse-engineering of the pins as well, but so far I found the fake blood pressure/O2 green LED to be on P00 :)

I'd be nice to also use the SWD interface. Looking at the .ini files used by Keil, we could figure out how to wrap the flash erase/write on OpenOCD; but this is far in the future :)

By the way, has anyone tried to dump the bootrom? I'll try that next!

**Comment by cocus** [comment]
I've dumped the bootrom, and it seems to be interesting. Some of those .ini files provided with the keil projects have some "Setup" function, and they seem to write stuff directly into memory. The bootloader does read that particular value RIGHT at the beginning. So this is cool :) I'm referring to the `0x4000F0A8`. Not sure if anyone has already looked at this before; I really like diving deep in these kind of convoluted things :)

![imagen](https://github.com/user-attachments/assets/0df310f0-08e2-477a-a761-4e2a0c9664a4)

**Comment by cocus** [comment]
Oh, actually, a lot of the ROM stuff is documented on the `bb_rom_sym_m0.gdbsym` and/or `bb_rom_sym_m0.txt` :) Well, I just want to know how do they jump to the flash code, and where's the reset vector so I can start decompiling the dump

**Comment by pvvx** [comment]
The clock code on the PHY is usually based on [PHY62XX_SDK_1.1.8.rar](https://github.com/pvvx/PHY62x2/blob/master/SDK/PHY62XX_SDK_1.1.8.rar)\PHY62XX_SDK_1.1.8\example\ble_peripheral\wrist .

There is no point in decompiling the firmware unless you have a lot of extra time. Writing from scratch is easier and faster.

The ROM bootloader was decompiled and disassembled several years ago. Vulnerabilities were found. Based on this data, utilities were created in Python.

**Comment by Amir1387aht2** [comment]
@cocus So we should start from making new firmware right? But as you know it's not gcc based but pvvx has wrote a sdk for that, we should use that

Guys what about making a group in telegram and chat on that?

Contact me, I will make that group : @Do3p3iri

**Comment by cocus** [comment]
> The clock code on the PHY is usually based on [PHY62XX_SDK_1.1.8.rar](https://github.com/pvvx/PHY62x2/blob/master/SDK/PHY62XX_SDK_1.1.8.rar)\PHY62XX_SDK_1.1.8\example\ble_peripheral\wrist .

Oh I see, that example isn't there on newer SDKs. Cool to know. I bet the pinout matches and all.


> There is no point in decompiling the firmware unless you have a lot of extra time. Writing from scratch is easier and faster.

Right, I just wanted to have a feeling of how the binary image should look like, and how to produce it from GCC (and not keil, but basing my idea from the keil builds).




> The ROM bootloader was decompiled and disassembled several years ago. Vulnerabilities were found. Based on this data, utilities were created in Python.

Is this posted somewhere? I'd like to understand what it does, and if someone else already did it, I'll not spend much time on it. I was getting further into the decompilation :). I think the most interesting decompilation would be of the RF libraries rather than the bootloader. But oh well, everything counts!

And as a comment, thank you for your tools and your repo. Cheers from 🇦🇷 




> @cocus So we should start from making new firmware right? But as you know it's not gcc based but pvvx has wrote a sdk for that, we should use that

That SDK is the official one from the company that makes the chips, Phy. It's made on Keil but it contains some GCC stuff. Interestingly enough, the Keil examples are mostly aimed to run in RAM (at least the ones from the latest SDK). My goal would be to run an app from the flash itself.

I don't know if the connections would match on all these watches, that's why I wanted to reverse engineer my dump (just slightly).

**Comment by Amir1387aht2** [comment]
@cocus So by running app from flash you mean you wanna make XIP work right? Idk this option available in this chip

**Comment by pvvx** [comment]
> I think the most interesting decompilation would be of the RF libraries rather than the bootloader.

Part of the RF code is in ROM.
The rest is completely translated and corrected into GCC sources.
https://github.com/pvvx/THB2/tree/master/bthome_phy6222/SDK/lib/rf


The ROM code contains several errors, so "path.c" is used.
At the time of working with THB2, there was no public access to the new SDK from "Phyplus" and newer SDKs were not found on the Internet.

XIP is in PHY6222,
XIP is not in PHY6202...


The OTA and boot ROM tables in THB2 SDK are not original. Completely changed by me to more suitable ones.
The original ones take up too much space in Flash, and the original OTA is terrible.

With SDK for GCC worked together with https://github.com/froloffw7.
Tried to make the chip work in "LE Long Range" (Coded PHY). Coded PHY does not work with the original SDK. In THB2, "Coded PHY" modes are not enabled - too many errors and shortcomings in the chip and ROM codes (RF).

**Comment by pvvx** [comment]
> Is this posted somewhere?

On Russian-language forums.
I don’t know English and don’t want to learn it - I use Google Translate.

> Oh I see, that example isn't there on newer SDKs. Cool to know. I bet the pinout matches and all.

Doesn't necessarily match.
There are many different PHY watch bracelets.
The most commonly used (Chinese) chips in bracelets do not have open documentation.
Some of them have been studied, but that was a long time ago...

PHY6202
![image](https://github.com/user-attachments/assets/0f348497-ff9f-4492-a00e-af2d84f953e9)
![Psb](https://github.com/user-attachments/assets/84b5a09b-c0e1-4560-939d-8baa50a6f69b)

![image](https://github.com/user-attachments/assets/7a3630d2-b87f-4c98-9ca3-a46d4f7a171d)

PHY6222
![image](https://github.com/user-attachments/assets/e9905716-fa0c-4416-8034-ccac89ed2143)

...

**Comment by Amir1387aht2** [comment]
@pvvx What IDE or code editor you used to build flash? Extension?

**Comment by cocus** [comment]
> https://github.com/pvvx/THB2/tree/master/bthome_phy6222/SDK/lib/rf

Oh cool! I should copy that repo and use it as a basis, since you already have the .hex build for flash figured out. I was looking for that!

**Comment by fla-t** [comment]
@cocus 

As for the lcd driver, I saw a post long ago [blog post](https://rbaron.net/blog/2021/07/06/Reverse-engineering-the-M6-smart-fitness-band.html). 

Disclaimer, the watch in the post have a different controller, but the LCD in this and my PHY one are same. Because I have both Phy and TLSR versions. 

He was able to pin point the name, I think its in the post. In the repo he has some example programs (but again not for the same controller but they might help). They are both same, it would not make business sense to use lcd that doesn't follow the industry common for wearables.

**Comment by fla-t** [comment]
Also @cocus,

You seem to be quite adept with microcontrollers, please keep updating this thread as u find more about the wearable.

**Comment by fla-t** [comment]
@pvvx 

When I run the script on Macbook, it doesn't work. It fails on ReadRevision(). I checked the function and it's not getting anything from the device. just empty byte string.

**Comment by cocus** [comment]
It seems like the controller is a st7735. Mine looks identical, I should
double check with a logic probe.


Excerpt from that article:

It is a 13-pin, 160x80 px, color SPI TFT display. It’s a little weird that
the data lines are called SDA and SCL (which are often seen in I²C
<https://en.wikipedia.org/wiki/I%C2%B2C> devices). I believe they are, in
fact, the MOSI and SCLK
<https://en.wikipedia.org/wiki/Serial_Peripheral_Interface> in disguise.

[image: Display pins]
*Overlaid pin labels on the display connector*

It uses the ST7735 driver (PDF)
<https://www.displayfuture.com/Display/datasheet/controller/ST7735.pdf> to
push pixels to the screen. This is good news, as this driver is relatively
popular among color displays. It’s featured in many maker-friendly products
and supported by Adafruit’s ST7735 library
<https://github.com/adafruit/Adafruit-ST7735-Library>. While Adafruit’s
library is built on top of Arduino abstractions and we’re very far from
that, it proved to be a great reference.

**Comment by Amir1387aht2** [comment]
@cocus Do you tried to build the firmware? It's first step

For display driver we can use u8g2 that can easily integrated to any mcu, it's not using arduino layer

**Comment by pvvx** [comment]
>  Because I have both Phy and TLSR versions.

![pcb_xx](https://github.com/user-attachments/assets/170ef5cf-caeb-4616-9721-3801229cb4de)

High consumption in sleep mode. No need to redesign the clock. Can be used with external power supply or battery as information board (touch light switch). With additional chips in this device everything is disassembled. I wrote a test, everything worked, but I abandoned this type of smart watch.

**Comment by cocus** [comment]
> @cocus Do you tried to build the firmware? It's first step
> 
> For display driver we can use u8g2 that can easily integrated to any mcu, it's not using arduino layer

I was able to build their firmware, but I need to strip it down to make a simple hello world out of it.

My watch is not like yours, I have the phy6222 and a 128x60 lcd similar to the one I've linked before. I need to figure out the connections of the pins. I can use the uart and one gpio I found.

**Comment by Amir1387aht2** [comment]
> > @cocus Do you tried to build the firmware? It's first step
> > 
> > For display driver we can use u8g2 that can easily integrated to any mcu, it's not using arduino layer
> 
> I was able to build their firmware, but I need to strip it down to make a simple hello world out of it.
> 
> My watch is not like yours, I have the phy6222 and a 128x60 lcd similar to the one I've linked before. I need to figure out the connections of the pins. I can use the uart and one gpio I found. 

The only problem I have is building firmware, i know the gpio and pins know my watch but I only need to build firmware 

How you build it? Can you guide me?

**Comment by fla-t** [comment]
@cocus 

Another instance where the driver of the watch was mentioned. [youtube video](https://youtu.be/sv58aPvIonw?t=2740)

Although the microcontroller is not PHY6222, but the LCD is similar to what I have. Might help you.

**Comment by Amir1387aht2** [comment]
@cocus Another video by same person is : https://youtu.be/UbP68mEhnUg?si=lqNKtkwcv_n03iQP

The mcu is same, probably lcd also
The thing we can try is st7735 and st7789

**Comment by Amir1387aht2** [comment]
@pvvx also this person mentioned you in his video https://youtu.be/UbP68mEhnUg?si=lqNKtkwcv_n03iQP

**Comment by fla-t** [comment]
@cocus 

Can you share your Makefile here, I was tweaking the one pvvx has in the THB2 repo but it's giving me weird error:
```
CC: source/main.c
In file included from source/main.c:6:
source/config.h:11:10: fatal error: string.h: No such file or directory
compilation terminated.
make: *** [Makefile:272: source/main.o] Error 1
```
Googled a bit they said use -ffreestanding didn't really helped. I have tried including the llvm folder where the string.h is residing in my system didn't work.

**Comment by pvvx** [comment]
THB2 used "Eclipse IDE for Embedded C and C++ Developers".
Everything is compiled using "GNU Tools ARM Embedded".

**Comment by cocus** [comment]
Yes, I'm not using an IDE to build this code, just vscode but using the GNU
arm toolchain and make.

That firmware is not for watches, neither the example of the SDK is a ready
to go firmware. I will try to get something flashed on my board first and
then try to slowly initialize the system up until the point that the screen
works. Please note that my watch has a small lcd (128x60 by the looks of
it) and not the bigger one.
I already watched the video of "Poking technology", in fact, that was the
trigger for buying two of these watches. Sadly, they're the phy6222 and not
the other variant of the soc. In any case, I'll let you know if I made some
progress.

**Comment by fla-t** [comment]
Oh I thought you actually flashed.

> That firmware is not for watches

Yes, that firmware is not for the watch we have (128x60) but I was just using its makefile for a simple uart repeater.

**Comment by fla-t** [comment]
Actually I figured it out, I was getting linker errors and many other errors. 

I just deleted all the old binaries and just installed from brew.

```
brew install --cask gcc-arm-embedded
```

**Comment by cocus** [comment]
I've had some time to tinker with the sources of the THB2. I've managed to flash something to the chip, and it writes to the UART when starting up. I'm facing some issues trying to get a damned timer to run, which I can't. HOWEVER, I was able to validate that my GPIO P00 is indeed the green led. Small steps.

I've also added some quality of life changes on the codebase, so now after uploading the hex, you can call another target of the makefile and it'll spawn a "miniterm.py" (modified slightly so it toggles the RTS and restarts the MCU when booting, so you don't lose any message; similar to platformio).

My branch is here https://github.com/cocus/phy6222-watch/tree/cocus/testing-watch. To run it, just run `make` on the `bthome_phy6222` dir (still need to clean it up, it's a WIP).
To compile, flash and monitor, you have this all in one command:
```
make -j10 && make flash && make terminal
```

(NOTE: Please change your tty or COM port in the makefile, on the variable `COM_PORT`; and also adjust how many cores you want to use for parallel build, I've used 10 in my example).

If there's a telegram group or discord server to join, I'd gladly join to ask many questions. 

Thanks!

**Comment by Amir1387aht2** [comment]
@cocus I made an telegram group, please join there, whoever want, please join : https://t.me/+GAc1NQBoNN42NWM8

**Comment by fla-t** [comment]
@Amir1387aht2 I am more comfortable with discord, can we do discord please 🙏 ?

**Comment by Amir1387aht2** [comment]
@fla-t So please send me friend request: @Amir1387ah#6605

**Comment by fla-t** [comment]
https://discord.gg/uR4nfJAV

join this, and let me close the issue

**Comment by fla-t** [comment]
Closing this issue went a little off track.

Anyone reading this later in the future: 

If you have connection problems, try removing the TM - DTR pin. 
It helped me and cocus, with the cheap chinese rectangular watches.
TM - DTR connection is in this repo is because pvvx took the temperature clock as an example.
